name: Build OpenSAMPLauncher

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 8 (Obrigatório)
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      - name: Aceitar Licenças Android
        run: yes | sdkmanager --licenses || true

      - name: Dar permissão ao Gradlew
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
          elif [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          fi

      - name: Compilar APK
        run: |
          if [ -f "gradlew" ]; then
            ./gradlew assembleDebug --stacktrace
          else
            cd android && ./gradlew assembleDebug --stacktrace
          fi

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: OpenSAMP-Debug
          path: "**/build/outputs/apk/debug/*.apk"
